### ISSUE TITLE
Bug causing wrong targets to be applied

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqtmdl#1]
There's something going on that results in the wrong target being applied (or no target being applied). I noticed numerous examples in the Klamath. I'm not sure how widespread this issue is or if it's just isolated to the Klamath.

An example is  for TP in Upper Klamath Lake at station KL0008.

Here are the TP target/s that appear to be applied:

geo_id | target_value | target_units | target_stat_base | season_start | season_end
-- | -- | -- | -- | -- | --
2019_UKLRN_KSD_KR | 0.035 | mg/l | single sample | 1-Jan | 31-Dec
2019_UKLRN_NPS_KR | 0.035 | mg/l | single sample | 1-Jan | 31-Dec

The correct targets should be 

geo_id | target_value | target_units | target_stat_base | season_start | season_end
-- | -- | -- | -- | -- | --
2002_UKLD_Lakes | 110 | ug/l | annual mean | 1-Jan | 31-Dec
2002_UKLD_Lakes | 30 | ug/l | seasonal mean | 1-Mar | 31-May

I checked the tmdl_db to make sure the geo_ids are applied correctly. They are so that is not the issue. I suspect there is something going on in which_target() or which_target_df(). I did a few small tests and I wasn't getting the correct info back.

**Comment by DEQcdonald** [comment]
I believe I've found the issue. The targets are assigned based on reach code and there are 19 stations in the Klamath with data that do not have reach codes in the stations db. 

  "KL0002"          "KL0003"          "KL0004"          "KL0005"          "KL0006"          "KL0007"          "KL0008"          "KL0009"         
"KL0011"          "CRLA_LTLMP_ST13" "CRLA_WQL12"      "CRLA_WQL13"      "421805121494800" "421935121530600" "422128121530603" "422500121502800"
"422519122005800" "422820122032100" "422620122004300"

**Comment by DEQcdonald** [comment]
Addressed in commit: https://github.com/DEQcdonald/st_report_files/commit/08a389324063c4535377f338cace79a03d826461
Stations with missing reach codes are removed and tagged in the stations_dropped dataframe.
