### ISSUE TITLE
Integrate AU changes into TMDL db

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqtmdl#3]
The IR team updated a number of AU IDs for the 2020 report. We need to also update the AUs in the TMDL db.
[AU_Fixes.xlsx](https://github.com/DEQcdonald/odeqtmdl/files/6858091/AU_Fixes.xlsx)

**Comment by rmichie** [comment]
Addressed in 3f33d75.

**Comment by DEQrmichie** [comment]
Addressed in 3f33d75.
